config/routes.rb
Rails.application.routes.draw do
  get 'know_me' => 'know_me#index'

  get 'logs/index'


  root 'home#index'
  get 'work' => 'works#index'
	get 'visitors' => 'visitors#index'
  get 'visitors/create' => 'know_me#save_visitor'
  get 'flat-details'=> 'flat_details#index'
  get 'logs' => 'logs#index'
  get 'visitors/page/:page_no' => 'visitors#page', as: :visitors_by_page
end

app/models/my_app.rb
class MyApp < ActiveRecord::Base
  has_many :my_app_uis
end

app/models/my_app_ui.rb
class MyAppUi < ActiveRecord::Base
  belongs_to :my_app, dependent: :destroy
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_one(:visitor_location)
  scope :all_important, -> { where(is_important: true) }

  def visit_time_humanize
    created_at.strftime("%d-%m-%Y, %H:%M")
  end
end

app/models/visitor_location.rb
class VisitorLocation < ActiveRecord::Base
  belongs_to(:visitor)


  scope :all_US, -> { where country_code: 'US'}



  def place
    %W[#{country_name} #{region_name}].reject(&:blank?).join(',')
  end

  def flag
    'flags/24/' + country_code.downcase + '.png'
  end
end

app/models/visitors_backup.rb
class VisitorsBackup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def pages(record_count, page_size)
    arr = (record_count.to_f / page_size.to_f).divmod(1)
    pages = arr[0]
    pages += 1 if arr[1] > 0
    pages
  end


end

app/controllers/flat_details_controller.rb
class FlatDetailsController < ApplicationController
  def index
  end
end

app/controllers/home.rb
class Home
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_visitor_country, only: [:index]

  def check_visitor_country
    return if params.include?('xxx007')
    visitor_host_ip = request.headers.include?(:HTTP_X_FORWARDED_FOR) ?
        request.headers[:HTTP_X_FORWARDED_FOR] :
        request.headers[:REMOTE_HOST]

    visitor_location = IPAddressLocation.get_location(visitor_host_ip)


    render(plain: 'Site Restricted for your location') if visitor_location['country_code'].eql?('IN')
  end

  def index
    # Save visitor to database
    # if web server is behind proxy/NAT, then HTTP_X_FORWARDED_FOR contains the IP of origin
    # if not then REMOTE_HOST contains the IP of origin
    visitor_host_ip = request.headers.include?(:HTTP_X_FORWARDED_FOR) ?
                      request.headers[:HTTP_X_FORWARDED_FOR] :
                      request.headers[:REMOTE_HOST]

    puts 'Curent visitor ' + visitor_host_ip
    unless Visitor.exists?(["remote_ip = ? and created_at >= ?", visitor_host_ip, 1.day.ago])
      Visitor.create( remote_ip: visitor_host_ip,
                      remote_host: request.headers[:REMOTE_IP].nil? ? 'NA': request.headers[:REMOTE_IP],
                      server_name: request.headers[:SERVER_NAME],
                      is_important: !ENV['NOT_IMPORTANT_VISITORS_IPs'].split.include?(visitor_host_ip)
                    )

    end
  end

end

app/controllers/know_me_controller.rb
class KnowMeController < ApplicationController
  before_filter :check_visitor_country, only: [:index]

  def check_visitor_country
    return if params.include?('xxx007')
    visitor_host_ip = request.headers.include?(:HTTP_X_FORWARDED_FOR) ?
        request.headers[:HTTP_X_FORWARDED_FOR] :
        request.headers[:REMOTE_HOST]

    visitor_location = IPAddressLocation.get_location(visitor_host_ip)


    render(plain: 'Site Restricted for your location') if visitor_location['country_code'].eql?('IN')
  end

  def index
    visitor_host_ip = request.headers.include?(:HTTP_X_FORWARDED_FOR) ?
        request.headers[:HTTP_X_FORWARDED_FOR] :
        request.headers[:REMOTE_HOST]

    puts 'Curent visitor ' + visitor_host_ip
    unless Visitor.exists?(["remote_ip = ? and created_at >= ?", visitor_host_ip, 1.day.ago])
      Visitor.create( remote_ip: visitor_host_ip,
                      remote_host: request.headers[:REMOTE_IP].nil? ? 'NA': request.headers[:REMOTE_IP],
                      server_name: request.headers[:SERVER_NAME],
                      is_important: !ENV['NOT_IMPORTANT_VISITORS_IPs'].split.include?(visitor_host_ip)
      )

    end
  end

  def save_visitor
    # Save visitor to database
    # if web server is behind proxy/NAT, then HTTP_X_FORWARDED_FOR contains the IP of origin
    # if not then REMOTE_HOST contains the IP of origin
    visitor_host_ip = request.headers.include?(:HTTP_X_FORWARDED_FOR) ?
        request.headers[:HTTP_X_FORWARDED_FOR] :
        request.headers[:REMOTE_HOST]

    puts 'Curent visitor ' + visitor_host_ip
    unless Visitor.exists?(["remote_ip = ? and created_at >= ?", visitor_host_ip, 1.day.ago])
      Visitor.create( remote_ip: visitor_host_ip,
                      remote_host: request.headers[:REMOTE_IP].nil? ? 'NA': request.headers[:REMOTE_IP],
                      server_name: request.headers[:SERVER_NAME],
                      is_important: !ENV['NOT_IMPORTANT_VISITORS_IPs'].split.include?(visitor_host_ip)
      )

    end

    render :nothing => true
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
    params[:page_no] = 1
    page
=begin
    @visitors = Visitor.all_important.reverse_order!
    @pages = 45
    respond_to do |format|
      format.html { render :index }
		  format.xml { render xml: @visitors}
      format.json { render json: @visitors }
    end
=end
  end

  def page
    page_no = params[:page_no].to_i if params.include?('page_no')

    end_index = page_no * 15
    start_index = end_index - 15
    @visitors = Visitor.all_important.reverse_order![start_index...end_index]

    @pages = pages(Visitor.all_important.count, 15)

    respond_to do |format|
      format.html { render :index }
      format.xml { render xml: @visitors}
      format.json { render json: @visitors }
    end


  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_url_from_model(model_name)
    Rails.application.routes.url_helpers.send('new_' + model_name.to_s.downcase + '_path')
  end

  def view_url_from_instance(instance)
    Rails.application.routes.url_helpers.send(instance.to_s.downcase + '_path')
  end

  def edit_url_from_instance(instance)
    Rails.application.routes.url_helpers.send('edit_' + instance.model_name.to_s.downcase + '_path', instance.id)
  end

  def method_path(parent_obj, attr_path)
    object = parent_obj
    attr_path.to_s.split('.').each do |item|
      object = object.send(item)
      return if object.nil?
    end
    object.to_s
  end

  def attr_foreign_key?(attr_name)
    attr_name[-3..-1].eql?('_id')
  end

  def attr_image?(attr_name)
    return false if attr_name.nil?

    attr_name[-4..-1].eql?('.png')
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def each_introduction
    introductions = YAML.load_file(Rails.root + 'db/introduction.yaml')

    question_no = 0
    introductions.each do |question|
      question_no += 1
      yield question_no, question['question'], question['answer']
    end

  end
end

app/helpers/know_me_helper.rb
module KnowMeHelper
  def each_introduction
    introductions = YAML.load_file(Rails.root + 'db/introduction.yaml')

    question_no = 0
    introductions.each do |question|
      question_no += 1
      yield question_no, question['question'], question['answer']
    end

  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/request_headers_helper.rb
module RequestHeadersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/flat_details/index.html.erb
<h3> Flat Details </h3>
<table class="show" >
  <% attributes = { Name: 'Atul Shimpi',
                    :'Project Name' => 'Saarthi Souvenir, Building Gold, 1st Floor, flat no C2 101',
                    :Rate => '5700 /-',
                    :'Corporate Discount' => '100 /-',
                    :'Total Cost' => '53,28,368 /-',
                    :'Loan Amount' => '41,85,000 /-',
                    :'Payment Made by bank' => '34,73,550 /-',
                    :'Payment made by me' => '9,41,000 /-',
                    :'Total Payment Made' => '44,14,550 /-',
                    :'Balance' => '9,13,818 /- (Bank : 7,11,450, Self : 2,02,368 /-)'
                  }
  %>

  <% attributes.each do |key, value| %>
    <tr>
      <td class="show2" > <%= key.to_s + ' : ' %> </td>
      <td> <%= value %> </td>
    </tr>
  <% end %>

</table>

app/views/home/index.html.erb
<h3>HiAtul.com</h3>

app/views/know_me/index.html.erb
<div id="side_bar"></div>
<div id= "title_name">atul</div>
<div id= "title_surname">shimpi</div>
<div id= "welcome">
  I am "Ruby on Rails" and "cloud" freelancer. Even though I work on "cloud", I am very down to earth.
</div>
<div id= "welcome_hr"></div>
<div id="profile_photo_cont_1">
  <div id="profile_photo"></div>
</div>
<div id="contact_details">
  <%= link_to('Work', work_path(xxx007: true))%> |
  <%= link_to('Github Profile', 'https://github.com/atul-shimpi',
              target: '_blank')%> |
  <%= link_to('Blogs', 'https://atulshimpi.wordpress.com/2015/08/16/installing-ruby-on-rails-on-windows/',
              target: '_blank')%> |
  <%= link_to('Visitors', visitors_path(xxx007: true),
              target: '_blank')%>
  <br>
  Cell : +91-9890979429<br>
  Email : shimpiatul@hotmail.com <br>
  Skype : shimpiatul
</div>
<div id="profile_photo_cont_2">
  <div id="profile_photo2"></div>
</div>

<div id="introduction_upper">
  <p><br>Hello,
  <br>Welcome to my site. Let me introduce myself..</p>
  <% each_introduction do |question_no, question, answer| %>
      <p id="question"><%= question %>
      <p id="answer"><%= answer.html_safe %></p>
      <% break if question_no == 7 %>
  <% end %>
</div>
<br>
<div id="introduction_lower">
  <br>
  <% each_introduction do |question_no, question, answer| %>
      <% if question_no > 7 %>
        <p id="question"><%= question %> </p>
        <p id="answer"><%= answer.html_safe %></p><br>
      <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>atul shimpi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if controller_name.eql?('know_me') %> <div class="app_window" > <% end %>
<% if controller_name.eql?('works') %> <div  class="app_window" style="height: 2860px" > <% end %>
<% if controller_name.eql?('visitors') %> <div  class="app_window app_window2" > <% end %>
<%= yield %>
</div>
<br>
</body>

<div id="copyright">
  <p>&copy; 2015 Atul Shimpi</p>
</div>
</html>

app/views/logs/index.html.erb
<pre> <%= File.read(Rails.root.join('log',"#{Rails.env}.log")) %> </pre>

app/views/partials/_button_tag.html.erb
<%= button_tag(button[:text],
               class: 'btn btn-primary btn-xs button',
               id: 'add',
               onclick: button[:onclick]
              )
%>

app/views/partials/_crud_menu_bar.html.erb
<div class="crud_menu_bar"></div>

app/views/partials/_delete_path.html.erb
<%= button_to :Delete,
              record,
              method: :delete,
              class: 'btn btn-xs btn-danger',
              data: { confirm: 'Are you sure ?'}
%>

app/views/partials/_drop_down_list.html.erb
<div class="form-group">
  <%= form.label(caption,
                 :class => 'control-label col-sm-1')
  %>

  <div class="col-md-4">
    <%= form.select(attr_name,
                    model.all.collect { |each_object| [each_object.name, each_object.id] },
                    {},
                    {:class => 'form-control'}
                   )
    %>
  </div>
</div>

app/views/partials/_new_edit.html.erb
<%= render 'partials/primary_task_title', title: object.new_record? ? 'Create' : 'Edit' %>

<%= form_for(object, :html => { :role => 'form', :class=>"form-horizontal"} ) do |this_form| %>
  <% exclude_attributes = local_assigns.key?(:exclude_attributes) ? exclude_attributes : [] %>
  <% exclude_attributes.push('id', 'created_at', 'updated_at', object.model_name.singular + '_id') %>
    <% nested_objects = local_assigns.key?(:nested_objects) ? nested_objects : [] %>
  <% exclude_attributes += nested_objects.collect { |nested_object| nested_object.model_name.singular + '_id' } %>

  <% object.attributes.keys.each do |key| %>
    <% next if exclude_attributes.include?(key) %>
    <%= render 'partials/text_field', form: this_form, caption: object.class.human_attribute_name(key), attr_name: key %>
  <% end %>

  <% nested_objects.each do |nested_object| %>
    <%= fields_for(nested_object) do |nested_form| %>
      <% nested_object.attributes.keys.each do |key| %>
        <% next if exclude_attributes.include?(key) %>
         <% if attr_foreign_key?(key) %>
           <%= render('partials/drop_down_list', form: nested_form,
                       model: object.class.human_attribute_name(key).camelcase.constantize,
                       caption: object.class.human_attribute_name(key), attr_name: key)
           %>
         <% else %>
           <%= render('partials/text_field', form: nested_form,
                       caption: object.class.human_attribute_name(key), attr_name: key)
           %>
         <% end %>
      <% end %>
    <% end %>
  <% end %>

  <%= render 'partials/save_cancel', form: this_form %>
<% end %>

app/views/partials/_page_links.html.erb
<% (1..pages).each do |page| %>
  <%= link_to(page, visitors_by_page_path(page)) %>
<% end %>

app/views/partials/_save_cancel.html.erb
<div class="form-group col-lg-8">
  <div class="col-sm-offset-1 col-sm-10">
    <%= form.submit('Save', :class=>'btn btn-primary btn-sm') %>
    <%= link_to 'Cancel', :back %>
  </div>
</div>

app/views/partials/_show.html.erb
<%= render 'partials/primary_task_title',
           title: local_assigns.key?(:title) ? title : record.model_name
%>

<table class="show-table" >
  <% sections = local_assigns.key?(:sections) ? sections : {} %>
  <% attributes.each_with_index do |attribute, index| %>

    <% if sections.value?(attribute[:name]) %>
        <tr class="sections" >
          <td> <%= sections.key(attribute[:name]) %> </td>
        </tr>
    <% end %>

    <tr>
      <td class="show-row" > <%= attribute[:title].to_s + ' : ' %> </td>
      <td> <%= method_path(record, attribute[:name]) %> </td>
    </tr>

  <% end %>

</table>

app/views/partials/_show_all.html.erb
<h3><%= render 'partials/ui_title', title: title %></h3>

<table class='table table-striped table-condensed table-hover'>

  <% actions ||= :CRUD %>

  <% if actions.to_s.include?('C') %>
      <div id="crud_menu_bar">
        <div class="app_menu">  <%= link_to :New, new_url_from_model(records.model_name) %> </div>
      </div>
  <% end %>

  <% columns.push('') if actions.to_s.include?('R') %>
  <% columns.push('') if actions.to_s.include?('U') %>
  <% columns.push('') if actions.to_s.include?('D') %>

  <thead>
  <tr>
    <% columns.each do |column_title| %>
        <th><%= column_title %></th>
    <% end %>
  </tr>
  </thead>
  <br>

  <% records.each do |record| %>
      <tr>
        <% attributes.each do |attribute| %>
            <% data = method_path(record, attribute) %>
            <% align = (data.number? ? 'right' : 'left') unless data.nil? %>
            <% if attr_image?(data) %>
                <td>  <%= image_tag(data, {onerror:"this.style.display='none'"}) %>  </td>
            <% else %>
                <td align=<%= align %> > <%= data %></td>
            <% end %>
        <% end %>

        <% if actions.to_s.include?('R') %> <td> <%= link_to :View, record %> </td> <% end %>
        <% if actions.to_s.include?('U') %> <td> <%= link_to :Edit, edit_url_from_instance(record) %></td> <% end %>
        <% if actions.to_s.include?('D') %> <td> <%= render 'partials/delete_path', record: record %> </td>
        <% end %>
      </tr>
  <% end %>

</table>

<% if local_assigns[:page_links] %>
  <%= render('partials/page_links', page_links) %>
<% end %>

app/views/partials/_text_field.html.erb
<div class="form-group">
  <%= form.label(caption, :class => 'control-label col-sm-2') %>
  <div class="col-md-4">  <%= form.text_field(attr_name, :class => 'form-control') %>  </div>
</div>

app/views/partials/_ui_title.html.erb
<div class='ui_title'>
  <h4><%= title %></h4>
</div>

app/views/request_headers/index.html.erb
<h2>Visitors</h2>
<table>
	<th>
		<td>Date</td>
		<td>IP Address</td>
		<td>Host Name</td>
		<td>Server Name</td>
	</th>
	<% @request_headers.each do |request_header| %>
		<tr>
			<td><%= request_header.created_at %></td>
			<td><%= request_header.remote_ip %></td>
			<td><%= request_header.remote_host %></td>
			<td><%= request_header.server_name %></td>
		<tr>
	<% end %>
</table>

app/views/visitors/index.html.erb
<%= render(  'partials/show_all',
             title: 'Site Visitors',
             columns: [ '',
                       'Location',
                       'Time Zone',
                       'IP Address',
                       'Visited On'
                       ],
             records: @visitors,
             attributes: [:'visitor_location.flag',
                          :'visitor_location.place',
                          :'visitor_location.time_zone',
                          :remote_ip, :visit_time_humanize
                         ],
             actions: :none,
             page_links: {pages: @pages, page_url: 'visitors_by_page_path'}
           )
%>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<div id="client_area">
  <%= link_to('Back', root_path) if defined?(root_path)  %>
  <h6 id="ui_title">My Work</h6>

  <% MyApp.all.each do |my_app| %>
      <div class="work_divs">
        <div class="work_domain"><%= my_app.domain %></div>
        <div class="work_description"><%= my_app.description %></div>
        <div class="work_technologies">Technologies Used : <%= my_app.technologies %></div>

        <%= first_image_path = nil %>

        <div class="work_ui_links">
          <% my_app.my_app_uis.each_with_index do |ui, index| %>
            <% first_image_path ||= ui.image_path %>
              <% image = asset_path ui.image_path %>
              <%= if index == 0; link_to ui.name, '#', :remote => true, :onclick => "document.getElementById(#{my_app.id}).style.backgroundImage = 'url(#{image})';"; end %>

              <% if index > 0 %> | <%= link_to ui.name,
                                               '#',
                                               :remote => true,
                                               :onclick => "document.getElementById(#{my_app.id}).style.backgroundImage = 'url(#{image})';" %>
              <% end %>
          <% end %>

          <% if first_image_path.blank? %>
              <div  class="my_app_ui" >Confidential Work. Preview restricted</div>
          <% else %>
            <div id=<%= my_app.id %> class="my_app_ui" style="background-image: url(<%= asset_path  first_image_path %>);"></div>
          <% end %>


        </div>
      </div>
      <br><br>
  <% end %>

</div>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>